#! /usr/bin/env python
import sys
from player import Player
from dealer import Dealer
"""
Evolution Main Program that combines a dealer with some number of players
to run a complete game.
"""

def main(argv):
    num_players = argv
    players = []
    for _ in range(num_players):
        players.append(Player())
    dealer = Dealer(players)
    dealer.run()
    dealer.print_results()

if __name__ == '__main__':
    main(sys.argv[1])
