#!/bin/bash

cd evolution

echo -ne '\033c'
for f in *_tests.py; do
    echo $f
    python $f
    printf "\n"
done

cd ../tests/xstep
python ./test_xstep.py
cd ../step4
python ./test_step4.py
cd ../xsilly
python ./test_xsilly.py

exit 0
