#! /usr/bin/env python

"""
A test harness for the Dealer display method
"""

import sys
import json
import thread

import evolution.display
from evolution.convert import Convert
from evolution.dealer import Dealer

def main():
    message = sys.stdin.readlines()
    json_situation = ""
    for line in message:
        json_situation += line.rstrip('\n')
    json_situation = json.loads(json_situation)
    try:
        dealer = Convert.json_to_dealer(json_situation)
        evolution.display.display(dealer)
    except AssertionError:
        pass


if __name__ == "__main__":
    main()
