#! /usr/bin/env python

"""
A test harness for the Dealer feed1 method
"""

import sys
import json
from evolution.convert import Convert
from evolution.dealer  import Dealer

def main():
    message = sys.stdin.readlines()
    json_situation = ""
    for line in message:
        json_situation += line.rstrip('\n')
    json_situation = json.loads(json_situation)
    try:
        dealer = Convert.json_to_dealer(json_situation)
        dealer.feed1()
        print json.dumps(Convert.dealer_to_json(dealer))
    except AssertionError:
        pass


if __name__ == "__main__":
    main()