#! /usr/bin/env python

"""
A test harness for the Dealer feed1 method
"""

import sys
import json
from evolution.convert import Convert
from evolution.dealer  import Dealer

def main():
    message = sys.stdin.readlines()
    json_message = ""
    for line in message:
        json_message += line.rstrip('\n')
    json_message = json.loads(json_message)
    try:
        dealer = Convert.json_to_dealer(json_message[0])
        step4  = Convert.json_to_step4(json_message[1])
        dealer.step4()
        print json.dumps(Convert.dealer_to_json(dealer))
    except AssertionError:
        pass


if __name__ == "__main__":
    main()
