#! /usr/bin/env python
import sys
from evolution.player import Player
from evolution.dealer import Dealer
"""
Evolution Main Program that combines a dealer with some number of players
to run a complete game.
"""

def print_results(dealer):
    """
    Prints player ID's and scores in descending order.
    """
    results = ""
    sorted_players = dealer.players
    sorted_players.sort(cmp=lambda p1, p2: p2.food_bag - p1.food_bag)
    for index, player in enumerate(sorted_players):
        results += "%d player id: %d score: %d\n" % (index + 1, player.name, player.food_bag)
    return results

def main(argv):
    num_players = int(argv)
    players = []
    for _ in range(num_players):
        players.append(Player())
    dealer = Dealer(players)
    dealer.run()
    print(print_results(dealer))

if __name__ == '__main__':
    main(sys.argv[1])
