#! /usr/bin/env python
import sys
from evolution.player import Player
from evolution.dealer import Dealer
from evolution.helpers import print_results
"""
Evolution Main Program that combines a dealer with some number of players
to run a complete game.
"""

def main(argv):
    num_players = int(argv)
    players = []
    for _ in range(num_players):
        players.append(Player())
    dealer = Dealer(players)
    dealer.run()
    print(print_results(dealer.get_scores()))

if __name__ == '__main__':
    main(sys.argv[1])
