#! /usr/bin/env python

import socket
import sys
from evolution.globals import *
from evolution.proxy_dealer import ProxyDealer
from evolution.player import Player


def main(adr, port, msg):
    # Create a TCP/IP socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    # Connect the socket to the port where the server is listening
    server_address = (adr, port)
    print >>sys.stderr, 'connecting to %s port %s' % server_address
    sock.connect(server_address)
    sock.sendall(msg)

    try:
        proxy_dealer = ProxyDealer(Player(), sock)
        proxy_dealer.listen_for_messages()
    except Exception:
        print("Closing connection")
        sock.shutdown(socket.SHUT_RDWR)
        sock.close()



help_message = """
Usage:
    ./xclient                   -- Connect to server on localhost via default port number.
    ./xclient <adr> <prt>       -- Connect to server at adr on port prt.
    ./xclient <adr> <prt> <tag> -- Connect to server at adr on port prt and player tagline tag.

Example:
    ./xclient 127.0.0.1 10000 "Blue Team"
        - Starts a player connection to localhost on port 10000 with the tagline "Blue Team"
"""


if __name__ == "__main__":
    args_len = len(sys.argv)
    if args_len == 1:
        main("127.0.0.1", LISTENING_PORT, PLAYER_TAG_LINE)
    elif args_len == 2 and sys.argv[1] == "-H":
        print(help_message)
    elif args_len == 3:
        main(sys.argv[1], int(sys.argv[2]), PLAYER_TAG_LINE)
    elif args_len == 4:
        main(sys.argv[1], int(sys.argv[2]), "\"" + sys.argv[3] + "\"")
    else:
        print("Wrong number of arguments given to xclient")
        print(help_message)
